# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lJudul = QtWidgets.QLabel(self.centralwidget)
        self.lJudul.setGeometry(QtCore.QRect(10, 20, 651, 81))
        self.lJudul.setAlignment(QtCore.Qt.AlignCenter)
        self.lJudul.setWordWrap(True)
        self.lJudul.setObjectName("lJudul")
        self.btnTraining = QtWidgets.QPushButton(self.centralwidget)
        self.btnTraining.setGeometry(QtCore.QRect(520, 670, 141, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnTraining.setFont(font)
        self.btnTraining.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"color: white;\n"
"border-radius:15px;\n"
"font-size: 150%;")
        self.btnTraining.setObjectName("btnTraining")
        self.btnScreenCreateDataset = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenCreateDataset.setGeometry(QtCore.QRect(30, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenCreateDataset.setFont(font)
        self.btnScreenCreateDataset.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenCreateDataset.setObjectName("btnScreenCreateDataset")
        self.btnScreenTraining = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenTraining.setGeometry(QtCore.QRect(240, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenTraining.setFont(font)
        self.btnScreenTraining.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenTraining.setObjectName("btnScreenTraining")
        self.btnScreenTesting = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenTesting.setGeometry(QtCore.QRect(450, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenTesting.setFont(font)
        self.btnScreenTesting.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenTesting.setObjectName("btnScreenTesting")
        self.btnKeluar = QtWidgets.QPushButton(self.centralwidget)
        self.btnKeluar.setGeometry(QtCore.QRect(630, 0, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnKeluar.setFont(font)
        self.btnKeluar.setStyleSheet("background-color:#FF3A3A;\n"
"text-weight: bold;\n"
"color: white;")
        self.btnKeluar.setObjectName("btnKeluar")
        self.lInfoClass = QtWidgets.QLabel(self.centralwidget)
        self.lInfoClass.setGeometry(QtCore.QRect(20, 730, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lInfoClass.setFont(font)
        self.lInfoClass.setText("")
        self.lInfoClass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoClass.setObjectName("lInfoClass")
        self.teClassSummary = QtWidgets.QTextEdit(self.centralwidget)
        self.teClassSummary.setEnabled(True)
        self.teClassSummary.setGeometry(QtCore.QRect(10, 160, 661, 501))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teClassSummary.setFont(font)
        self.teClassSummary.setReadOnly(True)
        self.teClassSummary.setObjectName("teClassSummary")
        self.pbTraining = QtWidgets.QProgressBar(self.centralwidget)
        self.pbTraining.setEnabled(True)
        self.pbTraining.setGeometry(QtCore.QRect(10, 680, 0, 0))
        self.pbTraining.setProperty("value", 0)
        self.pbTraining.setObjectName("pbTraining")
        self.lInfoProgress = QtWidgets.QLabel(self.centralwidget)
        self.lInfoProgress.setGeometry(QtCore.QRect(10, 680, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lInfoProgress.setFont(font)
        self.lInfoProgress.setMidLineWidth(0)
        self.lInfoProgress.setText("")
        self.lInfoProgress.setObjectName("lInfoProgress")
        self.pbLoading = QtWidgets.QProgressBar(self.centralwidget)
        self.pbLoading.setEnabled(True)
        self.pbLoading.setGeometry(QtCore.QRect(20, 810, 0, 0))
        self.pbLoading.setProperty("value", 24)
        self.pbLoading.setObjectName("pbLoading")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lJudul.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">KONVERSI BAHASA ISYARAT (SIBI) KE TEKS BAHASA INDONESIA DENGAN MENGGUNAKAN CONVOLUTIONAL NEURAL NETWORK (CNN)</span></p></body></html>"))
        self.btnTraining.setText(_translate("MainWindow", "Training"))
        self.btnScreenCreateDataset.setText(_translate("MainWindow", "Buat Dataset"))
        self.btnScreenTraining.setText(_translate("MainWindow", "Training"))
        self.btnScreenTesting.setText(_translate("MainWindow", "Testing"))
        self.btnKeluar.setText(_translate("MainWindow", "Keluar"))
