# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 885)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lJudul = QtWidgets.QLabel(self.centralwidget)
        self.lJudul.setGeometry(QtCore.QRect(10, 20, 651, 81))
        self.lJudul.setAlignment(QtCore.Qt.AlignCenter)
        self.lJudul.setWordWrap(True)
        self.lJudul.setObjectName("lJudul")
        self.leResult = QtWidgets.QLineEdit(self.centralwidget)
        self.leResult.setGeometry(QtCore.QRect(20, 670, 641, 41))
        self.leResult.setStyleSheet("border: 5px solid #FF823A;\n"
"font-size: 120%;\n"
"border-radius: 15px;\n"
"padding:5px 5px;\n"
"background: transparent;")
        self.leResult.setObjectName("leResult")
        self.lImageTesting = QtWidgets.QLabel(self.centralwidget)
        self.lImageTesting.setGeometry(QtCore.QRect(20, 170, 641, 480))
        self.lImageTesting.setStyleSheet("border: 5px solid #FF823A;\n"
"font-size: 40px;\n"
"border-radius: 15px;")
        self.lImageTesting.setAlignment(QtCore.Qt.AlignCenter)
        self.lImageTesting.setObjectName("lImageTesting")
        self.btnScreenCreateDataset = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenCreateDataset.setGeometry(QtCore.QRect(30, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenCreateDataset.setFont(font)
        self.btnScreenCreateDataset.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenCreateDataset.setObjectName("btnScreenCreateDataset")
        self.btnScreenTraining = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenTraining.setGeometry(QtCore.QRect(240, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenTraining.setFont(font)
        self.btnScreenTraining.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenTraining.setObjectName("btnScreenTraining")
        self.btnScreenTesting = QtWidgets.QPushButton(self.centralwidget)
        self.btnScreenTesting.setGeometry(QtCore.QRect(450, 110, 201, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnScreenTesting.setFont(font)
        self.btnScreenTesting.setStyleSheet("background-color:#38FF3D;\n"
"text-weight: bold;\n"
"border-radius:15px;\n"
"color:#282D39;\n"
"font-size: 150%;")
        self.btnScreenTesting.setObjectName("btnScreenTesting")
        self.btnKeluar = QtWidgets.QPushButton(self.centralwidget)
        self.btnKeluar.setGeometry(QtCore.QRect(820, 0, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnKeluar.setFont(font)
        self.btnKeluar.setStyleSheet("background-color:#FF3A3A;\n"
"text-weight: bold;\n"
"color: white;")
        self.btnKeluar.setObjectName("btnKeluar")
        self.lInfoClass = QtWidgets.QLabel(self.centralwidget)
        self.lInfoClass.setGeometry(QtCore.QRect(20, 730, 841, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lInfoClass.setFont(font)
        self.lInfoClass.setText("")
        self.lInfoClass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoClass.setObjectName("lInfoClass")
        self.lImageTesting2 = QtWidgets.QLabel(self.centralwidget)
        self.lImageTesting2.setGeometry(QtCore.QRect(670, 170, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lImageTesting2.setFont(font)
        self.lImageTesting2.setStyleSheet("border: 5px solid #FF823A;\n"
"font-size: 12px;\n"
"border-radius: 15px;")
        self.lImageTesting2.setAlignment(QtCore.Qt.AlignCenter)
        self.lImageTesting2.setObjectName("lImageTesting2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 540, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 640, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 490, 47, 13))
        self.label_3.setObjectName("label_3")
        self.hs_lv = QtWidgets.QSlider(self.centralwidget)
        self.hs_lv.setGeometry(QtCore.QRect(680, 510, 160, 22))
        self.hs_lv.setMaximum(255)
        self.hs_lv.setOrientation(QtCore.Qt.Horizontal)
        self.hs_lv.setObjectName("hs_lv")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(680, 590, 47, 13))
        self.label_6.setObjectName("label_6")
        self.hs_hs = QtWidgets.QSlider(self.centralwidget)
        self.hs_hs.setGeometry(QtCore.QRect(680, 610, 160, 22))
        self.hs_hs.setMaximum(255)
        self.hs_hs.setOrientation(QtCore.Qt.Horizontal)
        self.hs_hs.setObjectName("hs_hs")
        self.hs_hh = QtWidgets.QSlider(self.centralwidget)
        self.hs_hh.setGeometry(QtCore.QRect(680, 560, 160, 22))
        self.hs_hh.setMaximum(255)
        self.hs_hh.setOrientation(QtCore.Qt.Horizontal)
        self.hs_hh.setObjectName("hs_hh")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(680, 390, 47, 13))
        self.label.setObjectName("label")
        self.hs_ls = QtWidgets.QSlider(self.centralwidget)
        self.hs_ls.setGeometry(QtCore.QRect(680, 460, 160, 22))
        self.hs_ls.setMaximum(255)
        self.hs_ls.setOrientation(QtCore.Qt.Horizontal)
        self.hs_ls.setObjectName("hs_ls")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 440, 47, 13))
        self.label_2.setObjectName("label_2")
        self.hs_hv = QtWidgets.QSlider(self.centralwidget)
        self.hs_hv.setGeometry(QtCore.QRect(680, 660, 160, 22))
        self.hs_hv.setMaximum(255)
        self.hs_hv.setOrientation(QtCore.Qt.Horizontal)
        self.hs_hv.setObjectName("hs_hv")
        self.hs_lh = QtWidgets.QSlider(self.centralwidget)
        self.hs_lh.setGeometry(QtCore.QRect(680, 410, 160, 22))
        self.hs_lh.setMaximum(255)
        self.hs_lh.setOrientation(QtCore.Qt.Horizontal)
        self.hs_lh.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.hs_lh.setObjectName("hs_lh")
        self.lInfoClassBottom = QtWidgets.QLabel(self.centralwidget)
        self.lInfoClassBottom.setGeometry(QtCore.QRect(20, 810, 841, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lInfoClassBottom.setFont(font)
        self.lInfoClassBottom.setText("")
        self.lInfoClassBottom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoClassBottom.setObjectName("lInfoClassBottom")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lJudul.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">KONVERSI BAHASA ISYARAT (SIBI) KE TEKS BAHASA INDONESIA DENGAN MENGGUNAKAN CONVOLUTIONAL NEURAL NETWORK (CNN)</span></p></body></html>"))
        self.leResult.setPlaceholderText(_translate("MainWindow", "Hasil dari prediksi disini"))
        self.lImageTesting.setText(_translate("MainWindow", "Video Stream"))
        self.btnScreenCreateDataset.setText(_translate("MainWindow", "Buat Dataset"))
        self.btnScreenTraining.setText(_translate("MainWindow", "Training"))
        self.btnScreenTesting.setText(_translate("MainWindow", "Testing"))
        self.btnKeluar.setText(_translate("MainWindow", "Keluar"))
        self.lImageTesting2.setText(_translate("MainWindow", "Video Stream"))
        self.label_5.setText(_translate("MainWindow", "High H"))
        self.label_4.setText(_translate("MainWindow", "High V"))
        self.label_3.setText(_translate("MainWindow", "Low V"))
        self.label_6.setText(_translate("MainWindow", "High S"))
        self.label.setText(_translate("MainWindow", "Low H"))
        self.label_2.setText(_translate("MainWindow", "Low S"))
